### ISSUE TITLE
`.zim/modules/environment/init.zsh:setopt:16: no such option: CD_SILENT` when launching shell

### ISSUE THREAD

**Issue by eturkes** [zimfw/environment#5]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  
When launching a fresh instance of Zsh, I get the message in the title. It seems to be benign and does not appear until the shell is launched again. I get the message both on my daily use Zsh setup and following the repro example below, with no additional steps to the reproduce.

**Steps to reproduce**  
The fist 4 steps restart the shell with a clean installation of Zim in a temporary directory.
Use `exec zsh` when restarting the terminal or restarting the shell is needed.
1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. The message should appear

**Current behavior**  
`.zim/modules/environment/init.zsh:setopt:16: no such option: CD_SILENT` when launching a fresh instance of Zsh.

**Expected behavior**  
No warning message.

**Screenshots**  
N/A

**zimfw info**  
Note: I scrubbed some info from the System info section.
```
zimfw version: 1.6.2 (built at 2021-11-21 19:40:05 UTC, previous commit is a5fb148)
ZIM_HOME:      /home/eturkes/.zim
Zsh version:   5.6
System info:   Linux 5.3.18-59.34-default #1 SMP Thu Nov 11 12:18:45 UTC 2021 x86_64 GNU/Linux
```

**Additional context**  
N/A

**Comment by ericbn** [comment]
Ops, sorry about this. The option was introduced only in Zsh 5.8.
